### ISSUE TITLE
GetOrigSizes would return incorrect size when archive contains large file

### ISSUE THREAD

**Issue by cwlmyjm** [getnamo/7zip-cpp#29]
Hi, I am using your project to extract my archive. But I found that GetOrigSizes would return incorrect size when package contains large file like 10GB. This can be fixed in [UsefulFunctions.cpp](https://github.com/getnamo/7zip-cpp/blob/master/7zpp/UsefulFunctions.cpp) line 173, change intVal to uhVal. Then it will work for large archive contains large file. 😄

**Comment by getnamo** [comment]
Nice catch, feel free to open a pull request and I'll merge the change
