### ISSUE TITLE
dll

### ISSUE THREAD

**Issue by iraizo** [getnamo/7zip-cpp#47]
Is there a way to load the dll into memory without actually needing to ship it with the binary?

**Comment by getnamo** [comment]
That's not how DLLs work. They are platform specific binaries like a .exe. Linux and Mac equivalent would be called shared objects (.so).

**Comment by iraizo** [comment]
> 
> 
> That's not how DLLs work. They are platform specific binaries like a .exe. Linux and Mac equivalent would be called shared objects (.so).

Well is there an alternative to having the dll next to the binary?

**Comment by error454** [comment]
Look here under Search Order for Desktop Applications.
https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

**Comment by iraizo** [comment]
So thats a no then as i understand

**Comment by error454** [comment]
The user has to get the dll somehow. You either ship it with the software, like 99.99% of other software, or you make the user go get it on their own and put it into a folder that's in the dll search path. Most software that makes users DIY, do so for legal reasons, like mp3. Either way, this particular problem has nothing to do with this project, it's a generic dll question.

**Comment by iraizo** [comment]
Indeed, i guess i will download the dll before inititing the library
